
<h4 style="background-image: url(../../images/headline_bg.jpg);
    background-repeat: no-repeat;
    background-position: 0px bottom;
           padding-bottom: 7px;padding-top:15px;"><i class="fa fa-bookmark" style="color:#2980b9;"></i>
    <span style="font-size: 20px;">&nbsp;Welcome to <strong style="color:#2980b9;font-size: 24px;"> Kristu Jayanti College of Law</strong></span>
</h4>
<!--<hr />-->
<p style="text-align:justify;padding-top:5px;"> Kristu  Jayanti College of Law has been established as an institution to produce top-notch legal experts, who is capable of advancing rule of law and justice. The College’s faculty scholarship, its excellent facilities including a dedicated Law Library, serves to produce tomorrow's leaders in judiciary, academics and industry.</p>
<p align=justify>Law being the custodian of the society’s collective values, and also a key influencer, driver and regulator of its economic and social development, the importance of high-quality legal education cannot be overstated. Legal education not only produces great academicians, visionary judges and champion lawyers, but also law-abiding citizens, the cornerstone of democracy. Legal education in India, with a long history and proud heritage, has created many brilliant jurists and legal experts, and has shaped a multicultural and socio-economically complex country’s progress as a modern nation. In the process, it has also considerably evolved in its elements, discourses and methodologies. 
In the 21st century, which was born into a world of globalized trade and services and concomitant value systems, including those regarding a range of key matters, including consumerism, individual rights, democracy and sovereignty, environmental justice and minority rights, the need for state-of-the-art legal education in India has become more evident than ever. </p>
<p align=justify>At Kristu Jayanti College of Law, we understand that while meeting the critical need for producing principled, qualified, knowledgeable and internationally competitive lawyers, legal education should also serve as the foundation for the development of modern jurisprudence in order to lead the society towards a better and less unequal world. 
The law programmes offered at the College are designed with such deeper understanding about the emerging world, the changing needs of the society, and the values and aspirations of students. We have law and non-law faculty members, all highly qualified, with an impressive range and years of experience in providing high-quality legal education. The College currently offers dual degrees in B.A.LL.B, B.B.A.LL.B and B.Com LL.B with a keen focus on doctrinal and vocational training.  The courses offered under these programmes are aimed to train the students in constitutional law, international law, corporate and business law, contract law, environmental law etc.
Welcome to Kristu Jayanti College of Law!</p>
