<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 event-tab">
	<div class="panel panel-primary">
		<div class="panel-heading">
 National Conference on Criminology and Correctional Services Administration: Problems and Prospects
            <b class="panel-title pull-right">March 17<sup>th</sup> 2017</b>
            <div style="clear:both"></div>
        </div>
		<div class="panel-body">
		

			<p align=justify>The National Conference on "Criminology and Correctional Services Administration : Problems and Prospects",organized by the Department of Social Work, commenced on 17th March, 2017 at the SKE Auditorium of the college. The event was flagged off with a total of more than 100 delegates comprising of students from different colleges, researchers, professionals from various institutions and social workers from Non- Governmental Organizations across the country.</p>

			<p align=justify>The Inaugural Function included Dr. Jonas Richard A (Convenor of National Conference & Head, Department of Social Work, Kristu Jayanti College) welcoming the gathering and Rev.Fr. Lijo P Thomas (Financial Administrator & Head, Department of Computer Science, Kristu Jayanti College) delivered the Presidential Address. The Conference consisted of four technical sessions, paper presentations and a Panel Discussion. It was indeed an honour to have Shri H N Sathyanarayana Rao, IPS (Director General of Police and Inspector General of Prisons, Karnataka) as the Chief Guest who inaugurated the conference and set the pace by highlighting the ground realities of the problems faced by the individuals under trials and convict. Sir emphasized the importance and the need of this Conference in light of the rising crimes and lawlessness against humanity. Mr. John Jose (Student Coordinator of National Conference & II MSW student) proposed the Vote of thanks.</p>

			<p align=justify>The first technical session was conducted by Rev. Fr. Dr. Arockiam Kulandai S J, (Head, Department of Human Resources Development, St. Joseph's College, Trichy, Tamil Nadu) wherein Father spoke about the Sociology of Crime based on his experiences and case studies of the Sri Lankan refugees.</p>

			<p align=justify>The second technical session was on 'Crime & Police Accountability' by Dr. Sony Kunjappan (Assistant Professor, Centre for Studies in Social Management, School of Social Sciences, Central University of Gujarat). Dr. Kunjappan initiated the session by stating that though there have been various amendments to the Police Act of 1861, there is no mechanism to ensure police accountability in place. The speaker elaborated on some of the drawbacks in the system such as lack of legitimacy & absence of interaction between the institutions & citizens. Sir discussed some of the major problems with structure, the framework & the support system of the Criminal Justice System.</p>

			<p align=justify>The first day of the National Conference concluded with Paper Presentations session moderated by Dr. Sony Kunjappan, (Assistant Professor, and Centre for Studies in Social Management, School of Social Sciences, and Central University of Gujarat). The paper presentations hovered over the themes such as the Social Development model, Integrated Approach to Juvenile Delinquency, Police Accountability in Crime Prevention, Students Perspective in Rehabilitation of Women Prisoners, Repercussions Of Torture, Prisoners and their Mental Predicaments, Psychosocial Status of Sex Offenders, Life skill Training Approach to under trial inmates, Aggression and Stress Tolerance in Juvenile Delinquents and Forensic Investigation.</p>

			<p align=justify>The Second of the National Conference consisted of the third technical session by Dr. Thilagaraj (Director, and Academic Centre for Excellence, Digital Forensics, Tamil Nadu) who gave a review of the Juvenile Justice System in India. He mentioned about the viability of implementing laws which included the importance of Juvenile Justice and Criminal Justice. Sir emphasized the need for Social Re-integration from a juvenile’s perspective.</p>

			<p align=justify>The fourth technical session on "Victimology, Penology, and Criminal Justice System in India" was conducted by Dr. P Madhava Soma Sundaram (Professor, & Head, Dept. of Criminology and Criminal Justice, Manonmaniam Sundaranar University; Tirunelveli, Tamil Nadu). Sir gave an in-depth insight into the four levels of the Criminal Justice System namely the law making, investigating, objurgating and the correctional tiers .He also familiarized the audience with the shifting paradigms of the Correctional Services Administration.</p>

			<p align=justify>Panel Discussion on the Multidisciplinary Approach to Crime Prevention, moderated by Dr. Sony Kunjappan (Assistant Professor, Centre for Studies in Social Management, School of Social Sciences, Central University of Gujarat) marked the end of the academic venture. The session was initiated by Ms. Arlene Manoharan (Fellow and Programme Head-Juvenile Justice Program, Centre for Child and Law, National Law School of India University ,Bangalore). Ms. Manoharan, commented on Rethinking Punitive Approaches to addressing Juvenile Crime and recommended considering from the offender's point of view apart from the victim's point of view while delivering judgments.</p>

			<p align=justify>Dr. Kumaravel (Professor, Dept. of Social Work, Rajiv Gandhi National Institute for Youth Development, Sriperumbudur, Tamil Nadu) spoke about the Life Skills Approach to Crime Prevention. He enumerated the different approaches to Life Skills namely the classical, contemporary and the holistic approach and educated the participants on the role of Social Workers in advocacy, in the making of Development Policies and Practices and creating awareness in the society.</p>

			<p align=justify>Dr.Aravind G B. (Professor, Dept of Criminology and Forensic Science, Mahajana First Grade College, University of Mysore) reiterated the Behavioral Approach to Crime Prevention. He stated that the state of mind is the deciding factor of criminality and added that the Uncertainty of punishment and Lack of Speed of Punishment are the prime deterrents in stopping people from committing crimes. Sir also highlighted on the importance of associative learning where an individual modifies his behavior through various techniques.</p>

			<p align=justify>Dr. Chandrakanthi L. (Professor, University Law College, Bangalore University, Bengaluru) addressed the gathering on the Legal Approach to Crime Prevention. Dr. Chandrakanthi emphasized on the need to nationalize education to create awareness & prevent crime and advocated the importance of having knowledge of the relevant laws for the participation of the community. Madam spoke about Part IV Article 21 A of the constitution to highlight the importance of living with dignity and related the importance of educating families in this aspect.</p>

			<p align=justify>The National Conference concluded with a Valedictory Session. The dignitaries were Rev. Fr. Dr. Sebastian Vadakkumpadan, (Founder and Director of Prison Ministry of India, Bangalore), Rev. Fr. Som Zacharia (Director, Library & Infrastructure Development, Kristu Jayanti College) Dr. Jonas Richard A (Convener of the National Conference & Head, Department of Social Work, Kristu Jayanti College), Dr. I. Jerry Richards (Organizing Secretary of the Conference & Faculty, Department of Social Work, Kristu Jayanti College), Mr. Justin Jose (Student Coordinator of National Conference & I MSW student). Fr. Sebastian, in his Valedictory address highlighted the rehabilitation process of offenders and conveyed that in doing so the society preserves the dignity and worth of these offenders. He also shared his experiences in the field of Correctional Social work and underlined the need for manpower for offender rehabilitation. The valedictory session concluded with few participants giving their respective feedbacks on the National Conference and commended the College officials and the Department of Social Work for arranging an enriching academic platform.</p>
			
		<center><a href="https://www.facebook.com/pg/KristuJayantiCollege/photos/?tab=album&album_id=1313749708703898" target="_blank" class="btn btn-primary btn-sm">PHOTO GALLERY</a></center>
			
			
			
		</div>
	</div>
</div>